import "@angular/platform-browser";
import "@angular/platform-browser-dynamic";
import "@angular/core";
import "@angular/common";
import "@angular/forms";
import "@angular/http";
import "@angular/router";
import "ie-shim";
import "core-js/es6";
import "core-js/es7/reflect";
import "zone.js/dist/zone";
import "rxjs/add/operator/map";
import "rxjs/add/operator/mergeMap";
import "rxjs/Observable";
import "rxjs/Subject";
import "rxjs/Rx";
import "angular2-infinite-scroll";
import "angulartics2";
import "ng2-lazyload-image"